sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: qQfgOAKqzaqjwjMqJP88idskcp3qIWjY6aBVKEQwoqJIPixgXWi+077Bx1IkSGnymXiS5TG+y1g9xxcUnxhUlCwrugMwEozeUQBKTpj+o1eL66eR8+Q0mwzcBEElWZEbGr2Fct6XIvh3G5TCgIwTDjOt1sxpjtIWWyiykHB19pjmvwdGeHiEmGPsQQ3PSO7VKBSizUidp5Mad8b6qo6QIHZ4dW3VMBSh5Gyvulh3GmxcTuxr9bOoOFY6uMEAbfTrMnfZVN2R6L1VWu23LYTiAc3AHECLBmXnzGOTfY+qtow0ILDlGGVnsljTjuR5HEKLpJtt9ip4GGaT+q6VoIsRx/ZoijRKJUV8wAR0rW/DawzPXj4R1J11twtBtfmhtpYnU0ibRTGoRXYfLcLPR3lkgyMw8NO4yp/EYpaWY9PdUkki+9dqitLxhuX/+Rhq32mDj51uwQn6V+uM9l+wiVl6s/Bnk0s/nYBX2bCZ6ZlMH4nM5uodOEDHOrPboaTm4MzkO9FyGs38Xdvm30GFq6RI2FuCNx7p+6EQROLgZJOJJADK3tyh7HyfZKKxLDqn2t8wdb9T4QqqJXS1IcuZIW8bg4I4dUWMxZyuCeZndVf7Ly3ggScacLbmu/OKc6SOCK4EXptm4CYzVwRogI7OiNZ+Bsrgx23krpqenxEL7npGNoM=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: bFHnkWL1WChQRGR3dMyol7YZe34F7V31lEOU7hQNh/fyH2RbUD09KgY3aI/5hqoze51ApXpQkJzpzQh573/58xxie7SuIIimm7T6Dt/DKIoM1Ua724FEM1LCoM5NQx+bfcvEcWazD/nIvCrHvkLDitrP//gzLHAAeyXjSSViI3kfJOBejWJ8YcKASF+JScpIGjT1Mqtaq+A2CwBYnAIRXXt2ERCOED1z65ksI01LJ4Fab4022uFQtuKBbDJgpB9ZYUvVKqXSHGwb2Gi8lAEDvLViTWcFSKfEnQqSOyY7ZNOIPldt7IMm3VZe+LM9BcSOloqxLlrt/BOWGrG/lLQA7q7dx0fS4QWIDd7/sw21+LdfFbKSB2fDlrjWh8LnKLOo/IRLojOXMtd90edEpVODYAuF9NabHok+RS7B/HoN//8OaPytRzO6ABrCEIztqpz0z0T75iLwOTPPr/BcmCdjsmRDFlEFbP60Fz9C35UZjlfs0BX8ctkL1+tIws48fPo7t0c0aTV03LLWQR4MXXRiHFEkvSJc/G4nX+i+tNU62AXO879VEqB81Dbbdur5oImm7X+sPSbvrtiRNtno09Ce0m+ozmkDbkYAB5+PkZkxkjTwKwUoluGLMLFdQLxwj4ibV9E/n/DW8SknPYPHYTvLpTBxUt8u/dcvFBpWjQxysYA=
